version: '3'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:8.9.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./log:/var/log:ro # Mount your log directory here
    command: ["filebeat", "-e"]
    networks:
      - filebeat_kafka_network

networks:
  filebeat_kafka_network:
    driver: bridge