version: "3.6"
volumes:
  shared-workspace:
    name: "cassandra-workspace"
    driver: local
services:
  cassandra:
    image: 'bitnami/cassandra:latest'
    hostname: CASSANDRA
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    container_name: cassandra
    volumes:
      - shared-workspace:/opt/cassandra/schema.cql